name: intercampi
description: Intercampi - Unilab

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  yaml: ^3.1.2
  get_storage: ^2.1.1
  share_extend: ^2.0.0
  flutter_widget_from_html_core: ^0.14.9
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  intl: ^0.18.0
  url_launcher: ^6.1.14
  firebase_messaging: ^14.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/ui/assets/images/icon_app.png"
  min_sdk_android: 16
  remove_alpha_ios: true
  # to run: flutter pub run flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - pubspec.yaml
    - lib/ui/assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
